### ISSUE TITLE
Stuck on Verify.php

### ISSUE THREAD

**Issue by Akashgormani** [japakar/NewAutoEC#1]
i installed this script, when using shortlink it stucks on verify page.

![image](https://user-images.githubusercontent.com/58718708/75512662-f59ff200-5a13-11ea-946b-7e8a5ea24c96.png)

**Comment by japakar** [comment]
Try it without a shortlink, if it works, its the shortlink that is causing
the issue.
The last the script was updated, it installs and worked 100% without much
effort or editing.
